stages:
  train:
    cmd: python src/train.py experiment=catdog_ex +trainer.log_every_n_steps=1
    deps:
    - configs/train.yaml
    - src/train.py
    - data_catdog
    outs:
    - logs/train:
        cache: false
  eval:
    cmd: python src/eval.py ckpt_path=./logs/checkpoints/last.ckpt
    deps:
    - configs/eval.yaml
    - src/eval.py
    - data_catdog
    outs:
    - logs/eval:
        cache: false
  infer:
    cmd: python src/infer.py ckpt_path=./logs/checkpoints/last.ckpt
    deps:
    - configs/infer.yaml
    - src/infer.py
    - data_catdog
    outs:
    - logs/infer:
        cache: false