# Environment Settings
namespace: default
environment: prod
hostname: fastapi.localhost
modelName: "mambaout_base.in1k"

# Config Versions
configVersions:
  modelServer: v1
  redis: v1

# Config Versions
replica:
  webserver: 2
  modelserver: 2
# Web Server
webServer:
  image: 688567263021.dkr.ecr.ap-south-1.amazonaws.com/web_server:latest

# Model Server
modelServer:
  image: 688567263021.dkr.ecr.ap-south-1.amazonaws.com/model_server:latest
  resources:
    memory: "2Gi"
    cpu: "1000m"

# Redis
redis:
  image: 688567263021.dkr.ecr.ap-south-1.amazonaws.com/redis:7.4.1
  resources:
    memory: "200Mi"
    cpu: "200m"
  password: "default-password"