# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.log_dir}/checkpoints  # Specify the directory to save the checkpoint
  filename: "best-checkpoint"            # Set a fixed name for the checkpoint
  monitor: "val_loss"                    # Metric to monitor for saving the best model
  verbose: True                          # Enable logging of checkpointing events
  save_last: False                       # Do not save a separate last.ckpt file
  save_top_k: 1                          # Save only the best model
  mode: "min"                            # Minimize the monitored metric (e.g., val_loss)
  auto_insert_metric_name: False         # Avoid inserting the metric name into the filename
  save_weights_only: False               # Save the entire model (not just weights)
  every_n_train_steps: null              # Do not checkpoint based on training steps
  train_time_interval: null              # No time-based checkpointing
  every_n_epochs: null                   # No checkpointing based on epochs
  save_on_train_epoch_end: True          # Save the checkpoint at the end of the training epoch