# @package _global_

defaults:
  - override /hydra/sweeper: optuna

# We want to optimize for the highest test accuracy
optimization_metric: "test/acc_best"

# Override the experiment name
experiment_name: "catdog_vit_hparam_optimization"

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 3
    direction: maximize
    study_name: catdog_vit_hparam_optimization
    storage: null
    n_trials: 10
    n_jobs: 1

    params:
      # Model architecture params
      model.drop_rate: interval(0.0, 0.3)
      model.drop_path_rate: interval(0.0, 0.3)
      model.head_init_scale: interval(0.5, 1.0)
      data.batch_size: choice(8, 16, 32)