name: Train and Report
on:
  push:
    branches: [ feature/optuna_gradio ]
  pull_request:
    branches: [ main, feature/optuna_gradio ]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        env:
          UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
          GRPC_SSL_CIPHER_SUITES: HIGH+ECDSA

        run: |
          uv sync

      - name: Pull data from DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          GRPC_SSL_CIPHER_SUITES: HIGH+ECDSA

        run: |
          uv run dvc pull --jobs 8 -vv --no-run-cache

      - name: Train model
        run: |
          uv run dvc repro
